from django.urls import path, include
from rest_framework.routers import DefaultRouter
from . import views

# DefaultRouter auto-generates all URL patterns for each ViewSet
# No need to write path() for each endpoint manually
router = DefaultRouter()
router.register('courses', views.CourseViewSet)
router.register('students', views.StudentViewSet)
router.register('enrollments', views.EnrollmentViewSet)

urlpatterns = [
    #  from handson_01
    path('api/hello/', views.hello_view, name='hello'),

    # All ViewSet URLs are auto-generated by the router
    # This one line creates 5+ endpoints for EACH registered viewset
    path('api/', include(router.urls)),
]